version: "3.8"
services:
  backend:
    build: ./backend
    container_name: connectsy-backend
    restart: unless-stopped
    env_file: .env
    expose:
      - "3000"

  frontend:
    build: ./frontend
    container_name: connectsy-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: connectsy-nginx
    restart: unless-stopped
    ports:
      - "3000:80" # Expose backend API on port 3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
